version: '3.1'
services:
  todo_db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=todo
    container_name: ${DATABASE_HOST}

  task_management:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      - PORT=5000
      - NODE_ENV=development
    ports:
      - 5000:5000
    volumes:
      - .:/var/www/
      - /var/www/node_modules
    depends_on:
      - ${DATABASE_HOST}
